version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 8085:3306
    environment:
      MARIADB_ROOT_PASSWORD: pse2022

  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
